name = "ttsql-api"
main = "src/worker.js"
compatibility_date = "2024-07-24"
account_id = "2bc765ead68c800e3d2ad195ec8e8416"

[[d1_databases]]
binding = "DB"
database_name = "ttsql-database"
database_id = "268389d2-e781-4004-9291-178d5a9583f6"

[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "ttsql-database"
database_id = "268389d2-e781-4004-9291-178d5a9583f6"

[env.development]
[[env.development.d1_databases]]
binding = "DB"
database_name = "ttsql-database"
database_id = "268389d2-e781-4004-9291-178d5a9583f6"